name: Check PR Test

on:
  pull_request:
    branches:
      - master
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is in draft mode
        run: |
          if [ "${{ github.event.pull_request.draft }}" == "true" ]; then
            echo "PR is in draft mode, skipping workflow"
            exit 78
          fi
      - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: "1.37.0"
      - name: Run tests
        run: deno test --allow-env
